name: infa_care
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

  # Dependencies to be added here
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_rating_bar: ^0.0.8
  introduction_screen: ^3.1.12
  blurrycontainer: ^1.0.2
  rounded_loading_button_plus: ^3.0.1
  fluttertoast: ^8.2.4
  carousel_slider: ^4.2.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  location: ^5.0.3
  permission_handler: ^11.3.0
  animated_bottom_navigation_bar: ^1.3.3
  firebase_app_check: ^0.2.1+17
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
     - family: Medio
       fonts:
         - asset: assets/fonts/medio.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
